[general]
	live_config_reload = false
	import = [ "~/.config/alacritty/themes/tokyonight.toml" ]

[window]
	padding = { x = 5, y = 5 }
	opacity = 1.0
	dynamic_title = true

[font]
	normal = { family = "HackNerdFont", style = "Regular" }
	bold = { style = "Bold" }
	italic = { style = "Italic" }
	bold_italic = { style = "Bold Italic" }
	size = 11.50

[cursor]
	style = { shape = "Block", blinking = "Off" }

[keyboard]
	bindings = [
		{ key = "+", mods = "Control", action = "IncreaseFontSize" },
		{ key = "-", mods = "Control", action = "DecreaseFontSize" },
		{ key = "d", mods = "Control | Shift", action = "ScrollHalfPageDown" },
		{ key = "u", mods = "Control | Shift", action = "ScrollHalfPageUp" },
		{ key = "Up", mods = "Control | Shift", action = "ScrollLineUp" },
		{ key = "Down", mods = "Control | Shift", action = "ScrollLineDown" },
	]
